# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: riffraff
dist: ./build
before:
  hooks:
    - make clean
    - make configure
builds:
  - main: ./cmd/riffraff/main.go
    binary: riffraff
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
